global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: cebola-backend
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:3003"]
        labels:
          service: cebola-backend

  - job_name: blackbox-frontend
    metrics_path: /probe
    params:
      module: [http_frontend]
    static_configs:
      - targets:
          - http://web:3000/
        labels:
          service: cebola-frontend
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: blackbox-backend-health
    metrics_path: /probe
    params:
      module: [http_health_auth_optional]
    static_configs:
      - targets:
          - http://host.docker.internal:3003/api/auth/me
        labels:
          service: cebola-backend-health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
